import {
  CompletionItemKind,
  InsertTextFormat,
  MarkupKind,
} from "vscode-languageserver/node";
import type { CompletionItem, MarkupContent } from "vscode-languageserver/node";

export interface FunctionDoc {
  name: string;
  kind: CompletionItemKind;
  detail: string;
  documentation: string;
  signature?: string;
  insertText?: string;
  insertTextFormat?: InsertTextFormat;
}

function makeDoc(description: string): MarkupContent {
  return { kind: MarkupKind.Markdown, value: description };
}

// ---------------------------------------------------------------------------
// Keywords
// ---------------------------------------------------------------------------
export const KEYWORDS: CompletionItem[] = [
  { label: "sub", kind: CompletionItemKind.Keyword, detail: "Define a subroutine", insertText: "sub ${1:name} {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "alias", kind: CompletionItemKind.Keyword, detail: "Define a custom Beacon command", insertText: "alias ${1:name} {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "command", kind: CompletionItemKind.Keyword, detail: "Define an Aggressor Script console command" },
  { label: "on", kind: CompletionItemKind.Keyword, detail: "Register an event handler", insertText: "on ${1:event} {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "set", kind: CompletionItemKind.Keyword, detail: "Override a Cobalt Strike hook" },
  { label: "popup", kind: CompletionItemKind.Keyword, detail: "Define a popup menu", insertText: "popup ${1:name} {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "item", kind: CompletionItemKind.Keyword, detail: "Define a popup menu item" },
  { label: "if", kind: CompletionItemKind.Keyword, insertText: "if (${1:condition}) {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "else", kind: CompletionItemKind.Keyword },
  { label: "else if", kind: CompletionItemKind.Keyword },
  { label: "while", kind: CompletionItemKind.Keyword, insertText: "while (${1:condition}) {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "for", kind: CompletionItemKind.Keyword },
  { label: "foreach", kind: CompletionItemKind.Keyword, insertText: "foreach \\$${1:item} (${2:@list}) {\n\t$0\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "return", kind: CompletionItemKind.Keyword },
  { label: "break", kind: CompletionItemKind.Keyword },
  { label: "continue", kind: CompletionItemKind.Keyword },
  { label: "local", kind: CompletionItemKind.Keyword, detail: "Declare local variables", insertText: "local('\\$${1:var}');", insertTextFormat: InsertTextFormat.Snippet },
  { label: "global", kind: CompletionItemKind.Keyword },
  { label: "try", kind: CompletionItemKind.Keyword, insertText: "try {\n\t$0\n} catch \\$${1:err} {\n\t\n}", insertTextFormat: InsertTextFormat.Snippet },
  { label: "catch", kind: CompletionItemKind.Keyword },
  { label: "throw", kind: CompletionItemKind.Keyword },
  { label: "include", kind: CompletionItemKind.Keyword, detail: "Include another script" },
  { label: "import", kind: CompletionItemKind.Keyword },
];

// ---------------------------------------------------------------------------
// Hooks
// ---------------------------------------------------------------------------
export const HOOKS: CompletionItem[] = [
  { label: "BEACON_SLEEP_MASK", kind: CompletionItemKind.Constant, detail: "Hook: mask/unmask Beacon memory during sleep", documentation: makeDoc("Called to mask Beacon's memory when sleeping.\n\n**Parameters:**\n- `$1` — flag (1=mask, 0=unmask)\n- `$2` — beacon ID\n- `$3` — sleep duration") },
  { label: "BEACON_RDLL_GENERATE", kind: CompletionItemKind.Constant, detail: "Hook: generate a reflective DLL loader" },
  { label: "BEACON_RDLL_GENERATE_LOCAL", kind: CompletionItemKind.Constant, detail: "Hook: generate a reflective DLL loader (local)" },
  { label: "EXECUTABLE_ARTIFACT_GENERATOR", kind: CompletionItemKind.Constant, detail: "Hook: generate executable artifacts", documentation: makeDoc("Override how executable payloads are generated.") },
  { label: "HTMLAPP_EXE", kind: CompletionItemKind.Constant, detail: "Hook: customize HTML Application EXE" },
  { label: "HTMLAPP_POWERSHELL", kind: CompletionItemKind.Constant, detail: "Hook: customize HTML Application PowerShell" },
  { label: "POWERSHELL_COMMAND", kind: CompletionItemKind.Constant, detail: "Hook: customize PowerShell command format" },
  { label: "POWERSHELL_COMPRESS", kind: CompletionItemKind.Constant, detail: "Hook: customize PowerShell compression" },
  { label: "POWERSHELL_DOWNLOAD_CRADLE", kind: CompletionItemKind.Constant, detail: "Hook: customize PowerShell download cradle" },
  { label: "PSEXEC_SERVICE", kind: CompletionItemKind.Constant, detail: "Hook: customize PsExec service name/description" },
  { label: "PYTHON_COMPRESS", kind: CompletionItemKind.Constant, detail: "Hook: customize Python compression" },
  { label: "RESOURCE_GENERATOR", kind: CompletionItemKind.Constant, detail: "Hook: generate resource files" },
  { label: "RESOURCE_GENERATOR_VBS", kind: CompletionItemKind.Constant, detail: "Hook: generate VBScript resource" },
  { label: "SIGNED_APPLET_MAINCLASS", kind: CompletionItemKind.Constant },
  { label: "SIGNED_APPLET_RESOURCE", kind: CompletionItemKind.Constant },
  { label: "SMART_APPLET_MAINCLASS", kind: CompletionItemKind.Constant },
  { label: "SMART_APPLET_RESOURCE", kind: CompletionItemKind.Constant },
  { label: "APPLET_SHELLCODE_FORMAT", kind: CompletionItemKind.Constant, detail: "Hook: format shellcode for applet attacks" },
];

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------
export const EVENTS: CompletionItem[] = [
  { label: "beacon_checkin", kind: CompletionItemKind.Event, detail: "Fires when a Beacon calls home" },
  { label: "beacon_error", kind: CompletionItemKind.Event, detail: "Fires when a Beacon returns an error" },
  { label: "beacon_indicator", kind: CompletionItemKind.Event, detail: "Fires when Beacon posts an indicator" },
  { label: "beacon_initial", kind: CompletionItemKind.Event, detail: "Fires when a new Beacon checks in for the first time", documentation: makeDoc("Fired when a new Beacon session is established for the first time.\n\n**Parameters:**\n- `$1` — beacon ID") },
  { label: "beacon_initial_empty", kind: CompletionItemKind.Event, detail: "Fires when an empty Beacon checks in initially" },
  { label: "beacon_input", kind: CompletionItemKind.Event, detail: "Fires when a user types a Beacon command" },
  { label: "beacon_mode", kind: CompletionItemKind.Event, detail: "Fires when Beacon mode changes" },
  { label: "beacon_output", kind: CompletionItemKind.Event, detail: "Fires when Beacon returns output" },
  { label: "beacon_output_alt", kind: CompletionItemKind.Event, detail: "Fires for alternate Beacon output" },
  { label: "beacon_output_jobs", kind: CompletionItemKind.Event, detail: "Fires when Beacon returns jobs output" },
  { label: "beacon_output_ls", kind: CompletionItemKind.Event, detail: "Fires when Beacon returns 'ls' output" },
  { label: "beacon_output_ps", kind: CompletionItemKind.Event, detail: "Fires when Beacon returns 'ps' output" },
  { label: "beacon_tasked", kind: CompletionItemKind.Event, detail: "Fires when a Beacon is tasked" },
  { label: "disconnect", kind: CompletionItemKind.Event, detail: "Fires when a client disconnects from the team server" },
  { label: "event_action", kind: CompletionItemKind.Event, detail: "Fires for event log messages" },
  { label: "event_beacon_initial", kind: CompletionItemKind.Event, detail: "Fires for initial beacon event log" },
  { label: "event_join", kind: CompletionItemKind.Event, detail: "Fires when an operator joins" },
  { label: "event_newsite", kind: CompletionItemKind.Event, detail: "Fires when a new site is created" },
  { label: "event_notify", kind: CompletionItemKind.Event, detail: "Fires for general notifications" },
  { label: "event_nouser", kind: CompletionItemKind.Event, detail: "Fires when there are no users" },
  { label: "event_private", kind: CompletionItemKind.Event, detail: "Fires for private messages" },
  { label: "event_public", kind: CompletionItemKind.Event, detail: "Fires for public chat messages" },
  { label: "event_quit", kind: CompletionItemKind.Event, detail: "Fires when an operator quits" },
  { label: "heartbeat_1s", kind: CompletionItemKind.Event, detail: "Fires every 1 second" },
  { label: "heartbeat_5s", kind: CompletionItemKind.Event, detail: "Fires every 5 seconds" },
  { label: "heartbeat_10s", kind: CompletionItemKind.Event, detail: "Fires every 10 seconds" },
  { label: "heartbeat_15s", kind: CompletionItemKind.Event, detail: "Fires every 15 seconds" },
  { label: "heartbeat_30s", kind: CompletionItemKind.Event, detail: "Fires every 30 seconds" },
  { label: "heartbeat_1m", kind: CompletionItemKind.Event, detail: "Fires every 1 minute" },
  { label: "heartbeat_5m", kind: CompletionItemKind.Event, detail: "Fires every 5 minutes" },
  { label: "heartbeat_10m", kind: CompletionItemKind.Event, detail: "Fires every 10 minutes" },
  { label: "heartbeat_15m", kind: CompletionItemKind.Event, detail: "Fires every 15 minutes" },
  { label: "heartbeat_20m", kind: CompletionItemKind.Event, detail: "Fires every 20 minutes" },
  { label: "heartbeat_30m", kind: CompletionItemKind.Event, detail: "Fires every 30 minutes" },
  { label: "heartbeat_60m", kind: CompletionItemKind.Event, detail: "Fires every 60 minutes" },
  { label: "keylogger_hit", kind: CompletionItemKind.Event, detail: "Fires when keylogger data arrives" },
  { label: "profiler_hit", kind: CompletionItemKind.Event, detail: "Fires when system profiler data arrives" },
  { label: "ready", kind: CompletionItemKind.Event, detail: "Fires when the Aggressor Script environment is ready", documentation: makeDoc("Fired when Cobalt Strike is ready. Use this to initialize your script.") },
  { label: "sendmail_done", kind: CompletionItemKind.Event, detail: "Fires when a phishing email campaign is done" },
  { label: "sendmail_post", kind: CompletionItemKind.Event, detail: "Fires after each phishing email is sent" },
  { label: "sendmail_pre", kind: CompletionItemKind.Event, detail: "Fires before each phishing email is sent" },
  { label: "sendmail_start", kind: CompletionItemKind.Event, detail: "Fires when a phishing email campaign starts" },
  { label: "ssh_checkin", kind: CompletionItemKind.Event, detail: "Fires when an SSH session calls home" },
  { label: "ssh_error", kind: CompletionItemKind.Event },
  { label: "ssh_indicator", kind: CompletionItemKind.Event },
  { label: "ssh_initial", kind: CompletionItemKind.Event, detail: "Fires when a new SSH session checks in" },
  { label: "ssh_input", kind: CompletionItemKind.Event },
  { label: "ssh_output", kind: CompletionItemKind.Event },
  { label: "ssh_output_alt", kind: CompletionItemKind.Event },
  { label: "ssh_tasked", kind: CompletionItemKind.Event },
  { label: "web_hit", kind: CompletionItemKind.Event, detail: "Fires when a web server log entry is created" },
];

// ---------------------------------------------------------------------------
// Beacon command functions (bXxx)
// ---------------------------------------------------------------------------
export const BEACON_COMMANDS: CompletionItem[] = [
  { label: "barch", kind: CompletionItemKind.Function, detail: "barch($bid) — get Beacon architecture", documentation: makeDoc("Returns the architecture of a Beacon session.\n\n**Parameters:**\n- `$bid` — beacon ID\n\n**Returns:** `\"x86\"` or `\"x64\"`") },
  { label: "bargue_add", kind: CompletionItemKind.Function, detail: "bargue_add($bid, $arg) — add argument to injected process" },
  { label: "bargue_list", kind: CompletionItemKind.Function, detail: "bargue_list($bid) — list arguments for injected process" },
  { label: "bargue_remove", kind: CompletionItemKind.Function, detail: "bargue_remove($bid, $arg) — remove an argument" },
  { label: "bblockdlls", kind: CompletionItemKind.Function, detail: "bblockdlls($bid, $status) — block non-Microsoft DLLs from loading in child processes", documentation: makeDoc("Task a Beacon to block non-Microsoft DLLs from loading in spawned processes.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$status` — `true` to block, `false` to unblock") },
  { label: "bbrowser", kind: CompletionItemKind.Function, detail: "bbrowser($bid) — proxy the Beacon browser" },
  { label: "bbrowserpivot", kind: CompletionItemKind.Function, detail: "bbrowserpivot($bid, $pid, $port) — setup browser pivot" },
  { label: "bbrowserpivot_stop", kind: CompletionItemKind.Function, detail: "bbrowserpivot_stop($bid) — stop browser pivot" },
  { label: "bbypassuac", kind: CompletionItemKind.Function, detail: "bbypassuac($bid, $listener) — attempt UAC bypass", documentation: makeDoc("Spawn an elevated Beacon session via UAC bypass.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$listener` — listener name") },
  { label: "bcancel", kind: CompletionItemKind.Function, detail: "bcancel($bid, $file) — cancel a download in progress" },
  { label: "bcd", kind: CompletionItemKind.Function, detail: "bcd($bid, $dir) — change directory", documentation: makeDoc("Change the current working directory on the Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$dir` — target directory path") },
  { label: "bcheckin", kind: CompletionItemKind.Function, detail: "bcheckin($bid) — force a Beacon check-in" },
  { label: "bclear", kind: CompletionItemKind.Function, detail: "bclear($bid) — clear Beacon task queue" },
  { label: "bconnect", kind: CompletionItemKind.Function, detail: "bconnect($bid, $host, $port) — connect to a TCP Beacon" },
  { label: "bcovertvpn", kind: CompletionItemKind.Function, detail: "bcovertvpn($bid, $interface, $ip, $listener) — deploy Covert VPN" },
  { label: "bcp", kind: CompletionItemKind.Function, detail: "bcp($bid, $src, $dst) — copy a file" },
  { label: "bdata", kind: CompletionItemKind.Function, detail: "bdata($bid, $key) — get metadata from a Beacon", documentation: makeDoc("Retrieve a metadata field from a Beacon session.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$key` — field name (e.g. `'computer'`, `'user'`, `'pid'`, `'os'`)") },
  { label: "bdcsync", kind: CompletionItemKind.Function, detail: "bdcsync($bid, $domain, $user) — run DCSync to extract a password hash", documentation: makeDoc("Use DCSync to extract credentials from a domain controller.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$domain` — domain name (e.g. `CORP.LOCAL`)\n- `$user` — target user (e.g. `Administrator`)") },
  { label: "bdesktop", kind: CompletionItemKind.Function, detail: "bdesktop($bid) — start VNC desktop" },
  { label: "bdllinject", kind: CompletionItemKind.Function, detail: "bdllinject($bid, $pid, $dll) — inject a DLL into a process", documentation: makeDoc("Inject a DLL into a remote process.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$pid` — target process ID\n- `$dll` — path to local DLL file") },
  { label: "bdllload", kind: CompletionItemKind.Function, detail: "bdllload($bid, $pid, $dll) — load a DLL in a remote process" },
  { label: "bdllspawn", kind: CompletionItemKind.Function, detail: "bdllspawn($bid, $dll, $pipe, $arg, $time) — spawn a process and inject a DLL" },
  { label: "bdownload", kind: CompletionItemKind.Function, detail: "bdownload($bid, $file) — download a file from Beacon", documentation: makeDoc("Download a file from the target through Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$file` — remote file path to download") },
  { label: "bdrives", kind: CompletionItemKind.Function, detail: "bdrives($bid) — list drives on the target" },
  { label: "belevate", kind: CompletionItemKind.Function, detail: "belevate($bid, $exploit, $listener) — use an exploit to elevate privileges", documentation: makeDoc("Attempt privilege escalation using a registered exploit.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$exploit` — exploit name\n- `$listener` — listener name") },
  { label: "belevate_command", kind: CompletionItemKind.Function, detail: "belevate_command($bid, $exploit, $command) — run a command with elevated privileges" },
  { label: "berror", kind: CompletionItemKind.Function, detail: "berror($bid, $msg) — post an error message to a Beacon log" },
  { label: "bexecute", kind: CompletionItemKind.Function, detail: "bexecute($bid, $cmd) — execute a command without output capture", documentation: makeDoc("Execute a command on the target without capturing output.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$cmd` — command to execute") },
  { label: "bexecute_assembly", kind: CompletionItemKind.Function, detail: "bexecute_assembly($bid, $assembly, $args) — execute a .NET assembly in memory", documentation: makeDoc("Execute a .NET assembly in Beacon's process memory.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$assembly` — local path to the .NET assembly (.exe)\n- `$args` — arguments to pass to the assembly") },
  { label: "bexit", kind: CompletionItemKind.Function, detail: "bexit($bid) — exit the Beacon session" },
  { label: "bgetprivs", kind: CompletionItemKind.Function, detail: "bgetprivs($bid) — get current token privileges" },
  { label: "bgetsystem", kind: CompletionItemKind.Function, detail: "bgetsystem($bid) — attempt to get SYSTEM privileges", documentation: makeDoc("Attempt to elevate to SYSTEM privileges via service creation.\n\n**Parameters:**\n- `$bid` — beacon ID") },
  { label: "bgetuid", kind: CompletionItemKind.Function, detail: "bgetuid($bid) — get current user identity" },
  { label: "bhashdump", kind: CompletionItemKind.Function, detail: "bhashdump($bid) — dump password hashes from LSASS", documentation: makeDoc("Dump password hashes from the Windows SAM database via LSASS.\n\n**Parameters:**\n- `$bid` — beacon ID\n\n**Note:** Requires elevated privileges.") },
  { label: "binfo", kind: CompletionItemKind.Function, detail: "binfo($bid, $key) — retrieve Beacon metadata", documentation: makeDoc("Get a metadata field for a Beacon session.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$key` — metadata key: `id`, `pid`, `user`, `computer`, `os`, `arch`, `internal`, `external`, `last`, `session`, `listener`") },
  { label: "binject", kind: CompletionItemKind.Function, detail: "binject($bid, $shellcode, $arch) — inject shellcode into a process", documentation: makeDoc("Inject shellcode into a spawned process.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$shellcode` — shellcode bytes\n- `$arch` — `\"x86\"` or `\"x64\"`") },
  { label: "binjectsh", kind: CompletionItemKind.Function, detail: "binjectsh($bid, $pid, $shellcode, $arch) — inject shellcode into a specific PID" },
  { label: "binput", kind: CompletionItemKind.Function, detail: "binput($bid, $input) — simulate keyboard input in Beacon" },
  { label: "bipconfig", kind: CompletionItemKind.Function, detail: "bipconfig($bid) — run ipconfig on the target" },
  { label: "bjobkill", kind: CompletionItemKind.Function, detail: "bjobkill($bid, $jid) — kill a Beacon job" },
  { label: "bjobs", kind: CompletionItemKind.Function, detail: "bjobs($bid) — list Beacon jobs" },
  { label: "bjump", kind: CompletionItemKind.Function, detail: "bjump($bid, $method, $target, $listener) — lateral movement via jump", documentation: makeDoc("Lateral movement to another host.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$method` — jump method: `psexec`, `psexec64`, `psexec_psh`, `winrm`, `winrm64`\n- `$target` — target hostname\n- `$listener` — listener name") },
  { label: "bkerberos_ccache_use", kind: CompletionItemKind.Function, detail: "bkerberos_ccache_use($bid, $file) — use a Kerberos ccache file" },
  { label: "bkerberos_ticket_purge", kind: CompletionItemKind.Function, detail: "bkerberos_ticket_purge($bid) — purge Kerberos tickets" },
  { label: "bkerberos_ticket_use", kind: CompletionItemKind.Function, detail: "bkerberos_ticket_use($bid, $file) — use a Kerberos ticket file" },
  { label: "bkeylogger", kind: CompletionItemKind.Function, detail: "bkeylogger($bid) — start a keylogger" },
  { label: "bkill", kind: CompletionItemKind.Function, detail: "bkill($bid, $pid) — kill a process by PID" },
  { label: "blink", kind: CompletionItemKind.Function, detail: "blink($bid, $target, $port) — connect Beacons via TCP" },
  { label: "blog", kind: CompletionItemKind.Function, detail: "blog($bid, $msg) — post a message to a Beacon log" },
  { label: "blog2", kind: CompletionItemKind.Function, detail: "blog2($bid, $msg) — post a message to a Beacon log (alternate)" },
  { label: "bloginuser", kind: CompletionItemKind.Function, detail: "bloginuser($bid, $domain, $user, $pass) — create a token with credentials" },
  { label: "blogonpasswords", kind: CompletionItemKind.Function, detail: "blogonpasswords($bid) — dump credentials from logon sessions" },
  { label: "bls", kind: CompletionItemKind.Function, detail: "bls($bid, $path) — list files in a directory", documentation: makeDoc("List files in a directory via Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$path` — directory to list (default: current directory)") },
  { label: "bmimikatz", kind: CompletionItemKind.Function, detail: "bmimikatz($bid, $command) — run a Mimikatz command", documentation: makeDoc("Execute a Mimikatz command via Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$command` — Mimikatz command (e.g. `sekurlsa::logonpasswords`)") },
  { label: "bmkdir", kind: CompletionItemKind.Function, detail: "bmkdir($bid, $dir) — create a directory" },
  { label: "bmode", kind: CompletionItemKind.Function, detail: "bmode($bid, $mode) — change Beacon communication mode" },
  { label: "bmv", kind: CompletionItemKind.Function, detail: "bmv($bid, $src, $dst) — move a file" },
  { label: "bnet", kind: CompletionItemKind.Function, detail: "bnet($bid, $command, $arg) — run a net command", documentation: makeDoc("Run a network enumeration command via Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$command` — net subcommand: `computers`, `dclist`, `domain`, `domainlist`, `group`, `groups`, `localgroup`, `localgroups`, `sessions`, `share`, `user`, `users`, `view`\n- `$arg` — optional argument") },
  { label: "bnote", kind: CompletionItemKind.Function, detail: "bnote($bid, $note) — set a note on a Beacon" },
  { label: "bpassthehash", kind: CompletionItemKind.Function, detail: "bpassthehash($bid, $domain, $user, $hash) — use pass-the-hash to impersonate a user" },
  { label: "bpause", kind: CompletionItemKind.Function, detail: "bpause($bid, $ms) — pause execution for a number of milliseconds" },
  { label: "bportscan", kind: CompletionItemKind.Function, detail: "bportscan($bid, $targets, $ports, $disc, $maxconn) — port scan from Beacon", documentation: makeDoc("Run a port scan from the Beacon session.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$targets` — CIDR range or IP list\n- `$ports` — port range (e.g. `1-1024,3389,8080`)\n- `$disc` — discovery method: `arp`, `icmp`, `none`\n- `$maxconn` — max simultaneous connections") },
  { label: "bpowerpick", kind: CompletionItemKind.Function, detail: "bpowerpick($bid, $cmd) — run PowerShell without powershell.exe", documentation: makeDoc("Execute a PowerShell command using an unmanaged runspace (bypasses powershell.exe restrictions).\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$cmd` — PowerShell command") },
  { label: "bpowershell", kind: CompletionItemKind.Function, detail: "bpowershell($bid, $cmd) — execute a PowerShell command", documentation: makeDoc("Execute a PowerShell command via powershell.exe.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$cmd` — PowerShell command") },
  { label: "bpowershell_import", kind: CompletionItemKind.Function, detail: "bpowershell_import($bid, $file) — import a PowerShell script into Beacon memory" },
  { label: "bpowershell_import_clear", kind: CompletionItemKind.Function, detail: "bpowershell_import_clear($bid) — clear imported PowerShell scripts" },
  { label: "bppid", kind: CompletionItemKind.Function, detail: "bppid($bid, $ppid) — set parent PID for spawned processes", documentation: makeDoc("Set the parent process ID for processes spawned by Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$ppid` — parent process ID (0 to reset)") },
  { label: "bps", kind: CompletionItemKind.Function, detail: "bps($bid) — list processes" },
  { label: "bpsexec", kind: CompletionItemKind.Function, detail: "bpsexec($bid, $target, $share, $listener) — lateral movement via PsExec" },
  { label: "bpsexec_command", kind: CompletionItemKind.Function, detail: "bpsexec_command($bid, $target, $share, $cmd) — run a command via PsExec" },
  { label: "bpsexec_psh", kind: CompletionItemKind.Function, detail: "bpsexec_psh($bid, $target, $share, $listener) — PsExec lateral movement via PowerShell" },
  { label: "bpsinject", kind: CompletionItemKind.Function, detail: "bpsinject($bid, $pid, $arch, $ps1) — inject PowerShell into a process" },
  { label: "bpwd", kind: CompletionItemKind.Function, detail: "bpwd($bid) — get current working directory" },
  { label: "breg_query", kind: CompletionItemKind.Function, detail: "breg_query($bid, $hive, $path) — query a registry key" },
  { label: "breg_queryv", kind: CompletionItemKind.Function, detail: "breg_queryv($bid, $hive, $path, $value) — query a registry value" },
  { label: "bremote_exec", kind: CompletionItemKind.Function, detail: "bremote_exec($bid, $method, $target, $cmd) — remote execute a command", documentation: makeDoc("Execute a command on a remote host.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$method` — execution method: `wmi`, `winrm`, `psexec`\n- `$target` — target hostname\n- `$cmd` — command to run") },
  { label: "brev2self", kind: CompletionItemKind.Function, detail: "brev2self($bid) — revert to original token" },
  { label: "brm", kind: CompletionItemKind.Function, detail: "brm($bid, $file) — delete a file or directory" },
  { label: "brportfwd", kind: CompletionItemKind.Function, detail: "brportfwd($bid, $port, $rhost, $rport) — setup reverse port forward" },
  { label: "brportfwd_stop", kind: CompletionItemKind.Function, detail: "brportfwd_stop($bid, $port) — stop reverse port forward" },
  { label: "brun", kind: CompletionItemKind.Function, detail: "brun($bid, $cmd) — run a command and capture output", documentation: makeDoc("Run a command on the target and capture its output.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$cmd` — command to run") },
  { label: "brunas", kind: CompletionItemKind.Function, detail: "brunas($bid, $domain, $user, $pass, $cmd) — run a command as another user" },
  { label: "brunasadmin", kind: CompletionItemKind.Function, detail: "brunasadmin($bid, $cmd) — run a command in an elevated context" },
  { label: "brunu", kind: CompletionItemKind.Function, detail: "brunu($bid, $cmd) — run a command without impersonation" },
  { label: "bscreenshot", kind: CompletionItemKind.Function, detail: "bscreenshot($bid) — take a screenshot", documentation: makeDoc("Capture a screenshot from the target machine.\n\n**Parameters:**\n- `$bid` — beacon ID") },
  { label: "bsetenv", kind: CompletionItemKind.Function, detail: "bsetenv($bid, $var, $value) — set an environment variable" },
  { label: "bshell", kind: CompletionItemKind.Function, detail: "bshell($bid, $cmd) — execute a command via cmd.exe", documentation: makeDoc("Execute a shell command via `cmd.exe /c` on the target.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$cmd` — command string") },
  { label: "bshinject", kind: CompletionItemKind.Function, detail: "bshinject($bid, $pid, $arch, $shellcode) — inject shellcode into a PID" },
  { label: "bshspawn", kind: CompletionItemKind.Function, detail: "bshspawn($bid, $arch, $shellcode) — spawn a process and inject shellcode" },
  { label: "bsleep", kind: CompletionItemKind.Function, detail: "bsleep($bid, $seconds, $jitter) — set Beacon sleep interval", documentation: makeDoc("Set the Beacon callback interval and jitter.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$seconds` — sleep time in seconds\n- `$jitter` — jitter percentage (0-99)") },
  { label: "bsocks", kind: CompletionItemKind.Function, detail: "bsocks($bid, $port) — start SOCKS4a proxy", documentation: makeDoc("Start a SOCKS4a proxy server through the Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$port` — local port to listen on") },
  { label: "bsocks_stop", kind: CompletionItemKind.Function, detail: "bsocks_stop($bid) — stop SOCKS proxy" },
  { label: "bspawn", kind: CompletionItemKind.Function, detail: "bspawn($bid, $listener, $arch) — spawn a new Beacon" },
  { label: "bspawnas", kind: CompletionItemKind.Function, detail: "bspawnas($bid, $domain, $user, $pass, $listener) — spawn Beacon as another user" },
  { label: "bspawnto", kind: CompletionItemKind.Function, detail: "bspawnto($bid, $arch, $program) — set the spawn-to executable", documentation: makeDoc("Change the process Beacon uses when spawning post-exploitation jobs.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$arch` — `x86` or `x64`\n- `$program` — executable path (e.g. `%windir%\\syswow64\\notepad.exe`)") },
  { label: "bspawnu", kind: CompletionItemKind.Function, detail: "bspawnu($bid, $listener) — spawn Beacon without token impersonation" },
  { label: "bssh", kind: CompletionItemKind.Function, detail: "bssh($bid, $host, $port, $user, $pass, $listener) — connect to SSH host" },
  { label: "bssh_key", kind: CompletionItemKind.Function, detail: "bssh_key($bid, $host, $port, $user, $key, $listener) — connect to SSH host with key" },
  { label: "bstage", kind: CompletionItemKind.Function, detail: "bstage($bid, $target, $listener, $arch) — stage a payload" },
  { label: "bsteal_token", kind: CompletionItemKind.Function, detail: "bsteal_token($bid, $pid) — steal token from a process", documentation: makeDoc("Steal the access token from another process.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$pid` — process ID to steal token from") },
  { label: "bsudo", kind: CompletionItemKind.Function, detail: "bsudo($bid, $password, $cmd) — run a command with sudo (Linux)" },
  { label: "btask", kind: CompletionItemKind.Function, detail: "btask($bid, $msg) — post a task message to a Beacon log" },
  { label: "btimestomp", kind: CompletionItemKind.Function, detail: "btimestomp($bid, $src, $dst) — copy file timestamps" },
  { label: "bunlink", kind: CompletionItemKind.Function, detail: "bunlink($bid, $host) — disconnect a linked Beacon" },
  { label: "bupload", kind: CompletionItemKind.Function, detail: "bupload($bid, $file) — upload a file to Beacon", documentation: makeDoc("Upload a local file to the target through Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$file` — local file path to upload") },
  { label: "bupload_raw", kind: CompletionItemKind.Function, detail: "bupload_raw($bid, $remote, $data) — upload raw bytes to a file on the target" },
  { label: "bwdigest", kind: CompletionItemKind.Function, detail: "bwdigest($bid) — dump WDigest credentials" },
  { label: "bwinrm", kind: CompletionItemKind.Function, detail: "bwinrm($bid, $target, $listener) — lateral movement via WinRM" },
  { label: "bwmi", kind: CompletionItemKind.Function, detail: "bwmi($bid, $target, $listener) — lateral movement via WMI" },
];

// ---------------------------------------------------------------------------
// Beacon info functions
// ---------------------------------------------------------------------------
export const BEACON_INFO: CompletionItem[] = [
  { label: "beacons", kind: CompletionItemKind.Function, detail: "beacons() — return a list of all active Beacon sessions", documentation: makeDoc("Returns an array of hashes, one per active Beacon session.\n\nEach hash contains: `id`, `pid`, `user`, `computer`, `host`, `internal`, `os`, `arch`, `last`, `session`, `listener`.\n\n**Example:**\n```\nforeach $b (beacons()) {\n    println($b['computer']);\n}\n```") },
  { label: "beacon_ids", kind: CompletionItemKind.Function, detail: "beacon_ids() — return a list of all Beacon IDs" },
  { label: "beacon_info", kind: CompletionItemKind.Function, detail: "beacon_info($bid, $key) — get a metadata field from a Beacon", documentation: makeDoc("Get a single metadata field from a Beacon.\n\n**Parameters:**\n- `$bid` — beacon ID\n- `$key` — field: `id`, `pid`, `user`, `computer`, `os`, `arch`, `internal`, `external`, `last`, `session`, `listener`, `host`, `port`\n\n**Example:**\n```\n$os = beacon_info($bid, 'os');\n```") },
  { label: "beacon_data", kind: CompletionItemKind.Function, detail: "beacon_data($bid) — get full metadata hash for a Beacon" },
  { label: "beacon_commands", kind: CompletionItemKind.Function, detail: "beacon_commands() — list all Beacon commands" },
  { label: "beacon_command_describe", kind: CompletionItemKind.Function, detail: "beacon_command_describe($cmd) — get description of a Beacon command" },
  { label: "beacon_command_detail", kind: CompletionItemKind.Function, detail: "beacon_command_detail($cmd) — get detail of a Beacon command" },
  { label: "beacon_command_register", kind: CompletionItemKind.Function, detail: "beacon_command_register($cmd, $desc, $detail) — register a custom Beacon command", documentation: makeDoc("Register documentation for a custom Beacon alias.\n\n**Parameters:**\n- `$cmd` — command name\n- `$desc` — short description\n- `$detail` — full usage detail (shown by `help <cmd>`)") },
  { label: "beacon_elevator_describe", kind: CompletionItemKind.Function, detail: "beacon_elevator_describe($name) — describe an elevator" },
  { label: "beacon_elevator_register", kind: CompletionItemKind.Function, detail: "beacon_elevator_register($name, $desc, $detail) — register an elevation exploit" },
  { label: "beacon_elevators", kind: CompletionItemKind.Function, detail: "beacon_elevators() — list registered elevators" },
  { label: "beacon_execute_job", kind: CompletionItemKind.Function, detail: "beacon_execute_job($bid, $type, $command, $args) — execute a Beacon job" },
  { label: "beacon_exploit_describe", kind: CompletionItemKind.Function, detail: "beacon_exploit_describe($name) — describe an exploit" },
  { label: "beacon_exploit_register", kind: CompletionItemKind.Function, detail: "beacon_exploit_register($name, $arch, $desc, $detail) — register a post-ex exploit" },
  { label: "beacon_exploits", kind: CompletionItemKind.Function, detail: "beacon_exploits() — list registered exploits" },
  { label: "beacon_host_imported_script", kind: CompletionItemKind.Function, detail: "beacon_host_imported_script($bid, $data) — host an imported script in Beacon memory" },
  { label: "beacon_host_script", kind: CompletionItemKind.Function, detail: "beacon_host_script($bid, $data) — host a script in Beacon memory" },
  { label: "beacon_link", kind: CompletionItemKind.Function, detail: "beacon_link($bid, $host, $listener) — link to a Beacon peer" },
  { label: "beacon_remote_exec_method_describe", kind: CompletionItemKind.Function, detail: "beacon_remote_exec_method_describe($method) — describe a remote exec method" },
  { label: "beacon_remote_exec_method_register", kind: CompletionItemKind.Function, detail: "beacon_remote_exec_method_register($method, $desc, $detail) — register a remote exec method" },
  { label: "beacon_remote_exec_methods", kind: CompletionItemKind.Function, detail: "beacon_remote_exec_methods() — list remote exec methods" },
  { label: "beacon_remote_exploit_arch", kind: CompletionItemKind.Function, detail: "beacon_remote_exploit_arch($name) — get architecture of a remote exploit" },
  { label: "beacon_remote_exploit_describe", kind: CompletionItemKind.Function, detail: "beacon_remote_exploit_describe($name) — describe a remote exploit" },
  { label: "beacon_remote_exploit_register", kind: CompletionItemKind.Function, detail: "beacon_remote_exploit_register($name, $arch, $desc, $detail) — register a remote exploit" },
  { label: "beacon_remote_exploits", kind: CompletionItemKind.Function, detail: "beacon_remote_exploits() — list registered remote exploits" },
  { label: "beacon_remove", kind: CompletionItemKind.Function, detail: "beacon_remove($bid) — remove a Beacon from the UI" },
  { label: "beacon_stage_pipe", kind: CompletionItemKind.Function, detail: "beacon_stage_pipe($listener, $arch) — get named pipe stager" },
  { label: "beacon_stage_tcp", kind: CompletionItemKind.Function, detail: "beacon_stage_tcp($listener, $arch) — get TCP stager" },
];

// ---------------------------------------------------------------------------
// Aggressor Script utility functions
// ---------------------------------------------------------------------------
export const AGGRESSOR_FUNCTIONS: CompletionItem[] = [
  { label: "action", kind: CompletionItemKind.Function, detail: "action($msg) — log an action to the event log" },
  { label: "addTab", kind: CompletionItemKind.Function, detail: "addTab($title, $component, $icon) — add a tab to Cobalt Strike" },
  { label: "addVisualization", kind: CompletionItemKind.Function, detail: "addVisualization($name, $component) — add a visualization" },
  { label: "add_to_clipboard", kind: CompletionItemKind.Function, detail: "add_to_clipboard($text) — copy text to clipboard" },
  { label: "alias_clear", kind: CompletionItemKind.Function, detail: "alias_clear($name) — remove a Beacon alias" },
  { label: "applications", kind: CompletionItemKind.Function, detail: "applications() — get list of applications from targets" },
  { label: "archives", kind: CompletionItemKind.Function, detail: "archives() — get list of archives" },
  { label: "base64_decode", kind: CompletionItemKind.Function, detail: "base64_decode($str) — decode a Base64 string", documentation: makeDoc("Decode a Base64-encoded string.\n\n**Parameters:**\n- `$str` — Base64-encoded string\n\n**Returns:** decoded bytes") },
  { label: "base64_encode", kind: CompletionItemKind.Function, detail: "base64_encode($data) — encode data as Base64", documentation: makeDoc("Encode data as a Base64 string.\n\n**Parameters:**\n- `$data` — data to encode\n\n**Returns:** Base64 string") },
  { label: "call", kind: CompletionItemKind.Function, detail: "call($func, @args) — call a function by name" },
  { label: "credential_add", kind: CompletionItemKind.Function, detail: "credential_add($bid, %cred) — add a credential to the store", documentation: makeDoc("Add credentials to the Cobalt Strike credential store.\n\n**Parameters:**\n- `$bid` — beacon ID (source context)\n- `%cred` — hash with keys: `user`, `password`, `realm`, `source`, `host`") },
  { label: "credentials", kind: CompletionItemKind.Function, detail: "credentials() — get list of all stored credentials" },
  { label: "data_keys", kind: CompletionItemKind.Function, detail: "data_keys($type) — get data store keys" },
  { label: "data_query", kind: CompletionItemKind.Function, detail: "data_query($type, $key) — query the data store" },
  { label: "dialog", kind: CompletionItemKind.Function, detail: "dialog($title, %defaults, $callback) — create a dialog", documentation: makeDoc("Create a new dialog window.\n\n**Parameters:**\n- `$title` — dialog window title\n- `%defaults` — hash of default field values\n- `$callback` — lambda called when action button is pressed; receives `($bid, $button, %values)`\n\n**Returns:** dialog object") },
  { label: "dialog_description", kind: CompletionItemKind.Function, detail: "dialog_description($dialog, $text) — add a description to a dialog" },
  { label: "dialog_show", kind: CompletionItemKind.Function, detail: "dialog_show($dialog) — show a dialog" },
  { label: "dbutton_action", kind: CompletionItemKind.Function, detail: "dbutton_action($dialog, $label) — add an action button to a dialog" },
  { label: "dbutton_help", kind: CompletionItemKind.Function, detail: "dbutton_help($dialog, $url) — add a Help button" },
  { label: "drow_beacon", kind: CompletionItemKind.Function, detail: "drow_beacon($dialog, $key, $label) — add a Beacon selector row" },
  { label: "drow_checkbox", kind: CompletionItemKind.Function, detail: "drow_checkbox($dialog, $key, $label, $text) — add a checkbox row" },
  { label: "drow_combobox", kind: CompletionItemKind.Function, detail: "drow_combobox($dialog, $key, $label, @options) — add a combobox row" },
  { label: "drow_exploits", kind: CompletionItemKind.Function, detail: "drow_exploits($dialog, $key, $label) — add an exploits selector" },
  { label: "drow_file", kind: CompletionItemKind.Function, detail: "drow_file($dialog, $key, $label) — add a file picker row" },
  { label: "drow_interface", kind: CompletionItemKind.Function, detail: "drow_interface($dialog, $key, $label) — add a network interface selector" },
  { label: "drow_krbtgt", kind: CompletionItemKind.Function, detail: "drow_krbtgt($dialog, $key, $label) — add a Kerberos TGT selector" },
  { label: "drow_listener", kind: CompletionItemKind.Function, detail: "drow_listener($dialog, $key, $label) — add a listener selector row" },
  { label: "drow_listener_stage", kind: CompletionItemKind.Function, detail: "drow_listener_stage($dialog, $key, $label) — add a stageable listener selector" },
  { label: "drow_mailserver", kind: CompletionItemKind.Function, detail: "drow_mailserver($dialog, $key, $label) — add a mail server row" },
  { label: "drow_site", kind: CompletionItemKind.Function, detail: "drow_site($dialog, $key, $label) — add a web site selector" },
  { label: "drow_text", kind: CompletionItemKind.Function, detail: "drow_text($dialog, $key, $label) — add a text input row" },
  { label: "drow_text_big", kind: CompletionItemKind.Function, detail: "drow_text_big($dialog, $key, $label) — add a large text area row" },
  { label: "downloads", kind: CompletionItemKind.Function, detail: "downloads() — list all downloaded files" },
  { label: "elog", kind: CompletionItemKind.Function, detail: "elog($msg) — log a message to the event log", documentation: makeDoc("Log a message to the Cobalt Strike event log.\n\n**Parameters:**\n- `$msg` — message to log") },
  { label: "encode", kind: CompletionItemKind.Function, detail: "encode($str, $enc) — encode a string (e.g. base64)" },
  { label: "fireAlias", kind: CompletionItemKind.Function, detail: "fireAlias($bid, $alias, @args) — fire a Beacon alias" },
  { label: "fireEvent", kind: CompletionItemKind.Function, detail: "fireEvent($event, @args) — fire a custom event" },
  { label: "format_size", kind: CompletionItemKind.Function, detail: "format_size($bytes) — format bytes as human-readable size" },
  { label: "getAggressorClient", kind: CompletionItemKind.Function, detail: "getAggressorClient() — get the AggressorClient Java object" },
  { label: "gunzip", kind: CompletionItemKind.Function, detail: "gunzip($data) — decompress gzip data" },
  { label: "gzip", kind: CompletionItemKind.Function, detail: "gzip($data) — compress data with gzip" },
  { label: "highlight", kind: CompletionItemKind.Function, detail: "highlight($type, @ids, $color) — highlight rows in the UI", documentation: makeDoc("Highlight rows in a Cobalt Strike table view.\n\n**Parameters:**\n- `$type` — table type: `beacons`, `targets`, `credentials`, etc.\n- `@ids` — array of row IDs\n- `$color` — color name: `red`, `orange`, `yellow`, `green`, `blue`, `white`, `lime`, `cyan`, `purple`") },
  { label: "host_delete", kind: CompletionItemKind.Function, detail: "host_delete($addr) — remove a host from the hosts list" },
  { label: "host_info", kind: CompletionItemKind.Function, detail: "host_info($addr) — get info for a host" },
  { label: "host_update", kind: CompletionItemKind.Function, detail: "host_update($addr, %data) — update host info" },
  { label: "hosts", kind: CompletionItemKind.Function, detail: "hosts() — get list of all hosts" },
  { label: "iprange", kind: CompletionItemKind.Function, detail: "iprange($from, $to) — generate IP address range" },
  { label: "keystrokes", kind: CompletionItemKind.Function, detail: "keystrokes() — get list of captured keystrokes" },
  { label: "licenseKey", kind: CompletionItemKind.Function, detail: "licenseKey() — get the Cobalt Strike license key" },
  { label: "listener_create_ext", kind: CompletionItemKind.Function, detail: "listener_create_ext($name, $type, %options) — create a listener" },
  { label: "listener_delete", kind: CompletionItemKind.Function, detail: "listener_delete($name) — delete a listener" },
  { label: "listener_describe", kind: CompletionItemKind.Function, detail: "listener_describe($name) — describe a listener" },
  { label: "listener_info", kind: CompletionItemKind.Function, detail: "listener_info($name, $key) — get listener metadata" },
  { label: "listener_pivot_create", kind: CompletionItemKind.Function, detail: "listener_pivot_create($bid, $name, $type, %options) — create a pivot listener" },
  { label: "listener_restart", kind: CompletionItemKind.Function, detail: "listener_restart($name) — restart a listener" },
  { label: "listeners", kind: CompletionItemKind.Function, detail: "listeners() — list all listeners" },
  { label: "listeners_local", kind: CompletionItemKind.Function, detail: "listeners_local() — list local (stageable) listeners" },
  { label: "listeners_stageless", kind: CompletionItemKind.Function, detail: "listeners_stageless() — list stageless listeners" },
  { label: "localip", kind: CompletionItemKind.Function, detail: "localip() — get local IP address of this host" },
  { label: "menubar", kind: CompletionItemKind.Function, detail: "menubar($name, $popup) — add a menu to the menu bar" },
  { label: "mynick", kind: CompletionItemKind.Function, detail: "mynick() — get current operator nickname" },
  { label: "payload", kind: CompletionItemKind.Function, detail: "payload($listener, $type, $arch) — generate a payload" },
  { label: "pivots", kind: CompletionItemKind.Function, detail: "pivots() — list pivot listeners" },
  { label: "popup_clear", kind: CompletionItemKind.Function, detail: "popup_clear($name) — clear a popup menu" },
  { label: "pref_get", kind: CompletionItemKind.Function, detail: "pref_get($key) — get a preference value" },
  { label: "pref_get_list", kind: CompletionItemKind.Function, detail: "pref_get_list($key) — get a preference list value" },
  { label: "pref_set", kind: CompletionItemKind.Function, detail: "pref_set($key, $value) — set a preference value" },
  { label: "pref_set_list", kind: CompletionItemKind.Function, detail: "pref_set_list($key, @value) — set a preference list value" },
  { label: "privmsg", kind: CompletionItemKind.Function, detail: "privmsg($nick, $msg) — send a private message" },
  { label: "prompt_confirm", kind: CompletionItemKind.Function, detail: "prompt_confirm($msg, $title, $callback) — show a confirmation prompt", documentation: makeDoc("Show a yes/no confirmation dialog.\n\n**Parameters:**\n- `$msg` — message to display\n- `$title` — dialog title\n- `$callback` — lambda called when confirmed (no parameters)") },
  { label: "prompt_directory_open", kind: CompletionItemKind.Function, detail: "prompt_directory_open($title, $callback) — show a directory chooser" },
  { label: "prompt_file_open", kind: CompletionItemKind.Function, detail: "prompt_file_open($title, $filter, $multi, $callback) — show a file open dialog" },
  { label: "prompt_file_save", kind: CompletionItemKind.Function, detail: "prompt_file_save($title, $callback) — show a file save dialog" },
  { label: "prompt_text", kind: CompletionItemKind.Function, detail: "prompt_text($msg, $default, $callback) — show a text input prompt", documentation: makeDoc("Show a text input dialog.\n\n**Parameters:**\n- `$msg` — prompt message\n- `$default` — default value\n- `$callback` — lambda receiving `($value)` when submitted") },
  { label: "range", kind: CompletionItemKind.Function, detail: "range($start, $end) — generate a numeric range" },
  { label: "say", kind: CompletionItemKind.Function, detail: "say($msg) — post a message to the team chat" },
  { label: "sbrowser", kind: CompletionItemKind.Function, detail: "sbrowser() — open the screenshot browser" },
  { label: "screenshots", kind: CompletionItemKind.Function, detail: "screenshots() — list all screenshots" },
  { label: "script_resource", kind: CompletionItemKind.Function, detail: "script_resource($file) — get path to a resource relative to this script", documentation: makeDoc("Get the absolute path to a resource file located alongside this script.\n\n**Parameters:**\n- `$file` — relative filename\n\n**Returns:** absolute path string") },
  { label: "separator", kind: CompletionItemKind.Function, detail: "separator() — add a separator to a menu" },
  { label: "services", kind: CompletionItemKind.Function, detail: "services() — list all profiled services" },
  { label: "show_error", kind: CompletionItemKind.Function, detail: "show_error($msg) — show an error dialog", documentation: makeDoc("Display an error message dialog.\n\n**Parameters:**\n- `$msg` — error message") },
  { label: "show_message", kind: CompletionItemKind.Function, detail: "show_message($msg) — show an info dialog", documentation: makeDoc("Display an information message dialog.\n\n**Parameters:**\n- `$msg` — message to display") },
  { label: "showVisualization", kind: CompletionItemKind.Function, detail: "showVisualization($name) — show a visualization" },
  { label: "site_host", kind: CompletionItemKind.Function, detail: "site_host($host, $port, $uri, $type, $data, $msg, $ssl) — host a file on Cobalt Strike's web server" },
  { label: "site_kill", kind: CompletionItemKind.Function, detail: "site_kill($id) — kill a hosted web site" },
  { label: "sites", kind: CompletionItemKind.Function, detail: "sites() — list all hosted web sites" },
  { label: "ssh_command_describe", kind: CompletionItemKind.Function, detail: "ssh_command_describe($cmd) — describe an SSH command" },
  { label: "ssh_command_detail", kind: CompletionItemKind.Function, detail: "ssh_command_detail($cmd) — get SSH command detail" },
  { label: "ssh_command_register", kind: CompletionItemKind.Function, detail: "ssh_command_register($cmd, $desc, $detail) — register an SSH command" },
  { label: "ssh_commands", kind: CompletionItemKind.Function, detail: "ssh_commands() — list SSH commands" },
  { label: "stager", kind: CompletionItemKind.Function, detail: "stager($listener, $arch) — generate a stager payload" },
  { label: "stager_bind_pipe", kind: CompletionItemKind.Function, detail: "stager_bind_pipe($listener, $arch) — generate a named pipe stager" },
  { label: "stager_bind_tcp", kind: CompletionItemKind.Function, detail: "stager_bind_tcp($listener, $arch, $port) — generate a TCP bind stager" },
  { label: "str_chunk", kind: CompletionItemKind.Function, detail: "str_chunk($str, $size) — split a string into chunks" },
  { label: "str_decode", kind: CompletionItemKind.Function, detail: "str_decode($str) — decode a string" },
  { label: "str_encode", kind: CompletionItemKind.Function, detail: "str_encode($str) — encode a string" },
  { label: "str_xor", kind: CompletionItemKind.Function, detail: "str_xor($data, $key) — XOR a string with a key", documentation: makeDoc("XOR encode/decode a string with a repeating key.\n\n**Parameters:**\n- `$data` — data to XOR\n- `$key` — XOR key") },
  { label: "sync_download", kind: CompletionItemKind.Function, detail: "sync_download($bid, $remote, $local) — synchronously download a file" },
  { label: "targets", kind: CompletionItemKind.Function, detail: "targets() — list all target hosts" },
  { label: "tbrowser", kind: CompletionItemKind.Function, detail: "tbrowser() — open the target browser" },
  { label: "tokenToEmail", kind: CompletionItemKind.Function, detail: "tokenToEmail($token) — convert a token to an email address" },
  { label: "transform", kind: CompletionItemKind.Function, detail: "transform($data, $type) — transform data (e.g. to hex)" },
  { label: "transform_vbs", kind: CompletionItemKind.Function, detail: "transform_vbs($data) — transform data to VBScript" },
  { label: "tstamp", kind: CompletionItemKind.Function, detail: "tstamp($ms) — convert milliseconds to a timestamp string" },
  { label: "url_open", kind: CompletionItemKind.Function, detail: "url_open($url) — open a URL in the system browser" },
  { label: "users", kind: CompletionItemKind.Function, detail: "users() — list connected operators" },
  { label: "vpn_interface_info", kind: CompletionItemKind.Function, detail: "vpn_interface_info($iface) — get VPN interface info" },
  { label: "vpn_interfaces", kind: CompletionItemKind.Function, detail: "vpn_interfaces() — list VPN interfaces" },
  { label: "vpn_tap_create", kind: CompletionItemKind.Function, detail: "vpn_tap_create($iface, $listener) — create a VPN TAP interface" },
  { label: "vpn_tap_delete", kind: CompletionItemKind.Function, detail: "vpn_tap_delete($iface) — delete a VPN TAP interface" },
];

// ---------------------------------------------------------------------------
// Sleep built-in functions
// ---------------------------------------------------------------------------
export const SLEEP_FUNCTIONS: CompletionItem[] = [
  // String
  { label: "strlen", kind: CompletionItemKind.Function, detail: "strlen($str) — return length of a string" },
  { label: "substr", kind: CompletionItemKind.Function, detail: "substr($str, $start, $len) — extract a substring" },
  { label: "left", kind: CompletionItemKind.Function, detail: "left($str, $n) — leftmost n characters" },
  { label: "right", kind: CompletionItemKind.Function, detail: "right($str, $n) — rightmost n characters" },
  { label: "mid", kind: CompletionItemKind.Function, detail: "mid($str, $start, $len) — middle substring" },
  { label: "split", kind: CompletionItemKind.Function, detail: "split($delim, $str) — split a string by delimiter" },
  { label: "join", kind: CompletionItemKind.Function, detail: "join($delim, @arr) — join array elements with a delimiter" },
  { label: "replace", kind: CompletionItemKind.Function, detail: "replace($str, $find, $repl) — replace all occurrences" },
  { label: "replaceAt", kind: CompletionItemKind.Function, detail: "replaceAt($str, $pos, $len, $repl) — replace at position" },
  { label: "strrep", kind: CompletionItemKind.Function, detail: "strrep($str, $find, $repl) — substitute substrings" },
  { label: "lc", kind: CompletionItemKind.Function, detail: "lc($str) — convert to lowercase" },
  { label: "uc", kind: CompletionItemKind.Function, detail: "uc($str) — convert to uppercase" },
  { label: "trim", kind: CompletionItemKind.Function, detail: "trim($str) — trim whitespace" },
  { label: "indexOf", kind: CompletionItemKind.Function, detail: "indexOf($str, $sub, $start) — find first index of substring" },
  { label: "lindexOf", kind: CompletionItemKind.Function, detail: "lindexOf($str, $sub) — find last index of substring" },
  { label: "matches", kind: CompletionItemKind.Function, detail: "matches($str, $pattern) — check if string matches regex" },
  { label: "matched", kind: CompletionItemKind.Function, detail: "matched() — get matched groups from last regex match" },
  { label: "asc", kind: CompletionItemKind.Function, detail: "asc($char) — ASCII code of a character" },
  { label: "chr", kind: CompletionItemKind.Function, detail: "chr($code) — character from ASCII code" },
  { label: "byteAt", kind: CompletionItemKind.Function, detail: "byteAt($str, $idx) — byte value at position" },
  { label: "charAt", kind: CompletionItemKind.Function, detail: "charAt($str, $idx) — character at position" },
  { label: "pack", kind: CompletionItemKind.Function, detail: "pack($fmt, @args) — pack values into binary data" },
  { label: "unpack", kind: CompletionItemKind.Function, detail: "unpack($fmt, $data) — unpack binary data" },
  { label: "tr", kind: CompletionItemKind.Function, detail: "tr($str, $from, $to) — transliterate characters" },
  // Array
  { label: "push", kind: CompletionItemKind.Function, detail: "push(@arr, $val) — append to array" },
  { label: "pop", kind: CompletionItemKind.Function, detail: "pop(@arr) — remove and return last element" },
  { label: "shift", kind: CompletionItemKind.Function, detail: "shift(@arr) — remove and return first element" },
  { label: "add", kind: CompletionItemKind.Function, detail: "add(@arr, $val) — add element to array" },
  { label: "remove", kind: CompletionItemKind.Function, detail: "remove(@arr, $val) — remove element from array" },
  { label: "removeAt", kind: CompletionItemKind.Function, detail: "removeAt(@arr, $idx) — remove element at index" },
  { label: "size", kind: CompletionItemKind.Function, detail: "size(@arr) — number of elements in array/hash" },
  { label: "sort", kind: CompletionItemKind.Function, detail: "sort(@arr) — sort array in place" },
  { label: "sorta", kind: CompletionItemKind.Function, detail: "sorta(@arr) — sort array ascending" },
  { label: "sortd", kind: CompletionItemKind.Function, detail: "sortd(@arr) — sort array descending" },
  { label: "sortn", kind: CompletionItemKind.Function, detail: "sortn(@arr) — sort array numerically" },
  { label: "reverse", kind: CompletionItemKind.Function, detail: "reverse(@arr) — reverse an array" },
  { label: "copy", kind: CompletionItemKind.Function, detail: "copy($obj) — deep copy an object" },
  { label: "filter", kind: CompletionItemKind.Function, detail: "filter($pred, @arr) — filter array by predicate" },
  { label: "map", kind: CompletionItemKind.Function, detail: "map($func, @arr) — apply function to each element" },
  { label: "reduce", kind: CompletionItemKind.Function, detail: "reduce($func, @arr) — reduce array to single value" },
  { label: "flatten", kind: CompletionItemKind.Function, detail: "flatten(@arr) — flatten nested arrays" },
  { label: "sublist", kind: CompletionItemKind.Function, detail: "sublist(@arr, $start, $end) — extract sub-array" },
  { label: "splice", kind: CompletionItemKind.Function, detail: "splice(@arr, $idx, $len, @repl) — remove/replace elements" },
  { label: "concat", kind: CompletionItemKind.Function, detail: "concat(@a, @b) — concatenate two arrays" },
  { label: "addAll", kind: CompletionItemKind.Function, detail: "addAll(@dst, @src) — add all elements from one array to another" },
  { label: "search", kind: CompletionItemKind.Function, detail: "search(@arr, $val) — search for a value in an array" },
  { label: "sum", kind: CompletionItemKind.Function, detail: "sum(@arr) — sum array values" },
  // Hash
  { label: "keys", kind: CompletionItemKind.Function, detail: "keys(%hash) — get hash keys" },
  { label: "values", kind: CompletionItemKind.Function, detail: "values(%hash) — get hash values" },
  { label: "putAll", kind: CompletionItemKind.Function, detail: "putAll(%dst, %src) — copy all entries from one hash to another" },
  { label: "ohash", kind: CompletionItemKind.Function, detail: "ohash() — create an ordered hash" },
  { label: "ohasha", kind: CompletionItemKind.Function, detail: "ohasha() — create an ordered hash (alternate)" },
  { label: "setMissPolicy", kind: CompletionItemKind.Function, detail: "setMissPolicy(%hash, $policy) — set hash miss policy" },
  { label: "setRemovalPolicy", kind: CompletionItemKind.Function, detail: "setRemovalPolicy(%hash, $policy) — set hash removal policy" },
  // Math
  { label: "abs", kind: CompletionItemKind.Function, detail: "abs($n) — absolute value" },
  { label: "int", kind: CompletionItemKind.Function, detail: "int($n) — convert to integer" },
  { label: "double", kind: CompletionItemKind.Function, detail: "double($n) — convert to double" },
  { label: "long", kind: CompletionItemKind.Function, detail: "long($n) — convert to long" },
  { label: "uint", kind: CompletionItemKind.Function, detail: "uint($n) — unsigned integer" },
  { label: "rand", kind: CompletionItemKind.Function, detail: "rand($n) — random number 0..n-1" },
  { label: "sqrt", kind: CompletionItemKind.Function, detail: "sqrt($n) — square root" },
  { label: "floor", kind: CompletionItemKind.Function, detail: "floor($n) — floor value" },
  { label: "ceil", kind: CompletionItemKind.Function, detail: "ceil($n) — ceiling value" },
  { label: "round", kind: CompletionItemKind.Function, detail: "round($n) — round to nearest integer" },
  { label: "log", kind: CompletionItemKind.Function, detail: "log($n) — natural logarithm" },
  { label: "exp", kind: CompletionItemKind.Function, detail: "exp($n) — e^n" },
  { label: "sin", kind: CompletionItemKind.Function, detail: "sin($n) — sine" },
  { label: "cos", kind: CompletionItemKind.Function, detail: "cos($n) — cosine" },
  { label: "tan", kind: CompletionItemKind.Function, detail: "tan($n) — tangent" },
  { label: "asin", kind: CompletionItemKind.Function, detail: "asin($n) — arc sine" },
  { label: "acos", kind: CompletionItemKind.Function, detail: "acos($n) — arc cosine" },
  { label: "atan", kind: CompletionItemKind.Function, detail: "atan($n) — arc tangent" },
  { label: "atan2", kind: CompletionItemKind.Function, detail: "atan2($y, $x) — arc tangent of y/x" },
  { label: "degrees", kind: CompletionItemKind.Function, detail: "degrees($n) — radians to degrees" },
  { label: "radians", kind: CompletionItemKind.Function, detail: "radians($n) — degrees to radians" },
  { label: "srand", kind: CompletionItemKind.Function, detail: "srand($seed) — seed the random number generator" },
  { label: "digest", kind: CompletionItemKind.Function, detail: "digest($algo, $data) — compute hash digest (md5, sha1, etc.)" },
  { label: "checksum", kind: CompletionItemKind.Function, detail: "checksum($data) — compute a checksum" },
  { label: "parseNumber", kind: CompletionItemKind.Function, detail: "parseNumber($str) — parse a number from string" },
  { label: "formatNumber", kind: CompletionItemKind.Function, detail: "formatNumber($n, $fmt) — format a number" },
  // Core/misc
  { label: "sleep", kind: CompletionItemKind.Function, detail: "sleep($ms) — pause execution for milliseconds (Sleep function, not Beacon)" },
  { label: "exit", kind: CompletionItemKind.Function, detail: "exit() — exit the script" },
  { label: "eval", kind: CompletionItemKind.Function, detail: "eval($code) — evaluate a string as code" },
  { label: "typeOf", kind: CompletionItemKind.Function, detail: "typeOf($val) — get type name of a value" },
  { label: "include", kind: CompletionItemKind.Function, detail: "include($file) — include another script file" },
  { label: "lambda", kind: CompletionItemKind.Function, detail: "lambda($block, %env) — create a closure/lambda" },
  { label: "invoke", kind: CompletionItemKind.Function, detail: "invoke($func, @args) — invoke a function reference" },
  { label: "function", kind: CompletionItemKind.Function, detail: "function($name) — get a function reference by name" },
  { label: "debug", kind: CompletionItemKind.Function, detail: "debug($flag) — enable/disable debug mode" },
  { label: "warn", kind: CompletionItemKind.Function, detail: "warn($msg) — print a warning message" },
  { label: "println", kind: CompletionItemKind.Function, detail: "println($msg) — print with newline" },
  { label: "print", kind: CompletionItemKind.Function, detail: "print($msg) — print without newline" },
  { label: "systemProperties", kind: CompletionItemKind.Function, detail: "systemProperties() — get Java system properties" },
  { label: "newInstance", kind: CompletionItemKind.Function, detail: "newInstance($class, @args) — create a Java instance" },
  { label: "cwd", kind: CompletionItemKind.Function, detail: "cwd() — get current working directory" },
  { label: "ls", kind: CompletionItemKind.Function, detail: "ls($dir) — list directory contents" },
  { label: "mkdir", kind: CompletionItemKind.Function, detail: "mkdir($dir) — create a directory" },
  { label: "deleteFile", kind: CompletionItemKind.Function, detail: "deleteFile($path) — delete a file" },
  { label: "openf", kind: CompletionItemKind.Function, detail: "openf($path) — open a file for reading" },
  { label: "closef", kind: CompletionItemKind.Function, detail: "closef($handle) — close a file handle" },
  { label: "readln", kind: CompletionItemKind.Function, detail: "readln($handle) — read a line from file" },
  { label: "writeb", kind: CompletionItemKind.Function, detail: "writeb($handle, $data) — write bytes to file" },
  { label: "lof", kind: CompletionItemKind.Function, detail: "lof($path) — length of a file in bytes" },
  { label: "formatDate", kind: CompletionItemKind.Function, detail: "formatDate($ms, $fmt) — format a date/time" },
  { label: "ticks", kind: CompletionItemKind.Function, detail: "ticks() — current time in milliseconds" },
  { label: "exec", kind: CompletionItemKind.Function, detail: "exec($cmd) — execute a system command" },
];

// ---------------------------------------------------------------------------
// All completions merged
// ---------------------------------------------------------------------------
export const ALL_COMPLETIONS: CompletionItem[] = [
  ...KEYWORDS,
  ...HOOKS,
  ...EVENTS,
  ...BEACON_COMMANDS,
  ...BEACON_INFO,
  ...AGGRESSOR_FUNCTIONS,
  ...SLEEP_FUNCTIONS,
];

// ---------------------------------------------------------------------------
// Hover lookup map
// ---------------------------------------------------------------------------
export const HOVER_MAP = new Map<string, MarkupContent>();

for (const item of ALL_COMPLETIONS) {
  if (item.label && (item.documentation || item.detail)) {
    const content = item.documentation as MarkupContent | undefined;
    if (content) {
      HOVER_MAP.set(item.label as string, content);
    } else if (item.detail) {
      HOVER_MAP.set(item.label as string, makeDoc(`\`${item.detail}\``));
    }
  }
}
